app:
  logger_level: 20
webdriver:
  version: 117
  headless: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
ptt:
  forum:
    - "Gossiping"
  n: 20
plurk:
  query:
    - "plurk"
  n: 60
facebook:
  page:
    - "facebook"
  n: 10
  delay: 5
dcard:
  forum:
    - "trending"
  n: 20
  delay: 5
  retry: 3
cna:
  keywords:
    - "社會"
  n: 99
webhook:
  discord:
    ptt: []
    plurk: []
    dcard: []
    facebook: []
    cna: []
